package caddy

import (
	"bytes"
	"fmt"
	"io"
	"net/http"
	"strings"

	"github.com/racso/poof/store"
)

// GenerateCaddyfile builds a complete Caddyfile from the given projects and
// redirects. Only pass projects whose containers are currently running.
// rootDomain is used to generate subpath routing blocks on the root site.
// poofHost (e.g. "poof.example.com") and poofPort are used to add a route
// for the Poof API itself, which runs on the host rather than in a container.
func GenerateCaddyfile(projects []store.Project, redirects []store.Redirect, snippets map[string]string, rootDomain, poofHost string, poofPort int, staticDir string) string {
	var b strings.Builder

	// Warning header.
	fmt.Fprintf(&b, "# AUTO-GENERATED BY POOF — DO NOT EDIT\n")
	fmt.Fprintf(&b, "# Manual routes go in %s/*.Caddyfile\n\n", staticDir)

	// Global options: keep the admin API binding intact after every sync.
	fmt.Fprintf(&b, "{\n\tadmin 0.0.0.0:2019\n}\n\n")

	// Import manually-managed Caddyfile snippets.  The glob pattern means
	// an empty (or missing) directory is fine — Caddy won't error.
	fmt.Fprintf(&b, "import %s/*.Caddyfile\n\n", staticDir)

	// Poof's own API — runs as a container on poof-net, reachable by name.
	if poofHost != "" {
		fmt.Fprintf(&b, "%s {\n\treverse_proxy poof:%d\n}\n\n", poofHost, poofPort)
	}

	// subpathLines collects handle_path directives grouped by root domain.
	subpathLines := map[string][]string{}

	for _, p := range projects {
		// Skip if the project's domain is already emitted as the poofHost block above.
		if poofHost != "" && p.Domain == poofHost {
			continue
		}

		if p.IsStatic() {
			staticRoot := fmt.Sprintf("/var/lib/poof/static/%s/current", p.Name)
			fmt.Fprintf(&b, "%s {\n\troot * %s\n", p.Domain, staticRoot)
			if p.Static == "spa" {
				fmt.Fprintf(&b, "\ttry_files {path} /index.html\n")
			}
			fmt.Fprintf(&b, "\tfile_server\n")
		} else {
			fmt.Fprintf(&b, "%s {\n\treverse_proxy poof-%s:%d\n", p.Domain, p.Name, p.Port)
		}
		if snip, ok := snippets[p.Name]; ok && snip != "" {
			for _, line := range strings.Split(snip, "\n") {
				if line != "" {
					fmt.Fprintf(&b, "\t%s\n", line)
				}
			}
		}
		fmt.Fprintf(&b, "}\n\n")

		if rootDomain != "" && p.Domain != rootDomain && p.Subpath != "disabled" {
			switch p.Subpath {
			case "redirect":
				subpathLines[rootDomain] = append(subpathLines[rootDomain],
					fmt.Sprintf("\thandle_path /%s/* {\n\t\tredir https://%s{uri} 301\n\t}", p.Name, p.Domain))
			case "proxy":
				if p.IsStatic() {
					staticRoot := fmt.Sprintf("/var/lib/poof/static/%s/current", p.Name)
					block := fmt.Sprintf("\thandle_path /%s/* {\n\t\troot * %s\n", p.Name, staticRoot)
					if p.Static == "spa" {
						block += "\t\ttry_files {path} /index.html\n"
					}
					block += "\t\tfile_server\n\t}"
					subpathLines[rootDomain] = append(subpathLines[rootDomain], block)
				} else {
					subpathLines[rootDomain] = append(subpathLines[rootDomain],
						fmt.Sprintf("\thandle_path /%s/* {\n\t\treverse_proxy poof-%s:%d\n\t}", p.Name, p.Name, p.Port))
				}
			}
		}
	}

	for domain, lines := range subpathLines {
		fmt.Fprintf(&b, "%s {\n%s\n}\n\n", domain, strings.Join(lines, "\n"))
	}

	for _, r := range redirects {
		fmt.Fprintf(&b, "%s {\n\tredir https://%s{uri} 301\n}\n\n", r.FromDomain, r.ToDomain)
	}

	return b.String()
}

// Reload posts the generated Caddyfile to the Caddy admin API for a
// zero-downtime config reload.
func Reload(adminURL, caddyfile string) error {
	url := strings.TrimRight(adminURL, "/") + "/load"
	resp, err := http.Post(url, "text/caddyfile", bytes.NewBufferString(caddyfile))
	if err != nil {
		return fmt.Errorf("caddy reload: %w", err)
	}
	defer resp.Body.Close()
	if resp.StatusCode != http.StatusOK {
		body, _ := io.ReadAll(resp.Body)
		return fmt.Errorf("caddy reload: status %d: %s", resp.StatusCode, strings.TrimSpace(string(body)))
	}
	return nil
}
