server {
    listen 80;

    location = /install {
        return 302 https://raw.githubusercontent.com/racso/poof/main/install.sh;
    }

    location / {
        root /usr/share/nginx/html;
        index index.html;
    }
}
