package github

import (
	"bytes"
	"crypto/rand"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"strings"

	"github.com/racso/poof/defaults"
	"golang.org/x/crypto/nacl/box"
)

const apiBase = "https://api.github.com"

// workflowTemplate is committed into each project repo at
// .github/workflows/poof-<name>.yml. Placeholders are replaced at commit time:
//   POOF_BRANCH        → branch to deploy on push
//   POOF_PATHS_BLOCK   → optional "    paths:\n      - ..." block (empty for root builds)
//   POOF_IMAGE_BASE    → Docker image base (without tag)
//   POOF_BUILD_ARGS    → docker build args ("." for root, "-f folder/Dockerfile folder" for subfolders)
//   POOF_PROJECT_NAME  → Poof! project name (may differ from GitHub repo name in monorepos)
//   POOF_PKG_NAME      → GHCR package name for cleanup
//   All projects in the same repo share a single POOF_TOKEN secret.
// workflowMarker is the tag checked before deleting a workflow file.
// Only files whose first line starts with this marker are considered Poof-managed.
const workflowMarker = "# [poof-auto-ci]"

const workflowTemplate = `# [poof-auto-ci] AUTO-GENERATED BY Poof! — CHANGES MAY BE OVERRIDDEN. DISABLE CI ON Poof! TO USE A CUSTOM FILE.
name: POOF_WORKFLOW_NAME

on:
  push:
    branches: ["POOF_BRANCH"]
POOF_PATHS_BLOCK
permissions:
  contents: read
  packages: write

jobs:
  deploy:
    if: vars.POOF_DISABLE != '1'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build and push image
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          IMAGE=POOF_IMAGE_BASE:${{ github.sha }}
          docker build -t $IMAGE POOF_BUILD_ARGS
          docker push $IMAGE
          echo "IMAGE=$IMAGE" >> $GITHUB_ENV

      - name: Deploy via Poof!
        run: |
          curl -fsSL -X POST "${{ secrets.POOF_URL }}/projects/POOF_PROJECT_NAME/deploy" \
            -H "Authorization: Bearer ${{ secrets.POOF_TOKEN }}" \
            -H "Content-Type: application/json" \
            -d "{\"image\": \"${{ env.IMAGE }}\"}"

      - name: Clean up old images
        uses: actions/delete-package-versions@v5
        with:
          package-name: POOF_PKG_NAME
          package-type: container
          min-versions-to-keep: 3
          delete-only-untagged-versions: false
`

// staticWorkflowDockerTemplate is used for static projects that have a Dockerfile.
// The Dockerfile builds the site; the output is extracted from /poof in the container.
const staticWorkflowDockerTemplate = `# [poof-auto-ci] AUTO-GENERATED BY Poof! — CHANGES MAY BE OVERRIDDEN. DISABLE CI ON Poof! TO USE A CUSTOM FILE.
name: POOF_WORKFLOW_NAME

on:
  push:
    branches: ["POOF_BRANCH"]
POOF_PATHS_BLOCK
permissions:
  contents: read

jobs:
  deploy:
    if: vars.POOF_DISABLE != '1'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build static site
        run: |
          docker build -t poof-build POOF_BUILD_ARGS
          docker create --name poof-extract poof-build
          docker cp poof-extract:/poof ./poof-output
          docker rm poof-extract

      - name: Deploy to Poof!
        run: |
          tar -czf site.tar.gz -C ./poof-output .
          curl -fsSL -X POST "${{ secrets.POOF_URL }}/projects/POOF_PROJECT_NAME/deploy/static" \
            -H "Authorization: Bearer ${{ secrets.POOF_TOKEN }}" \
            -H "Content-Type: application/gzip" \
            --data-binary @site.tar.gz
`

// staticWorkflowDirectTemplate is used for static projects without a Dockerfile.
// The source directory is tarred and uploaded directly.
const staticWorkflowDirectTemplate = `# [poof-auto-ci] AUTO-GENERATED BY Poof! — CHANGES MAY BE OVERRIDDEN. DISABLE CI ON Poof! TO USE A CUSTOM FILE.
name: POOF_WORKFLOW_NAME

on:
  push:
    branches: ["POOF_BRANCH"]
POOF_PATHS_BLOCK
permissions:
  contents: read

jobs:
  deploy:
    if: vars.POOF_DISABLE != '1'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Deploy to Poof!
        run: |
          tar -czf site.tar.gz -C POOF_FOLDER .
          curl -fsSL -X POST "${{ secrets.POOF_URL }}/projects/POOF_PROJECT_NAME/deploy/static" \
            -H "Authorization: Bearer ${{ secrets.POOF_TOKEN }}" \
            -H "Content-Type: application/gzip" \
            --data-binary @site.tar.gz
`

type Client struct {
	token string
}

func NewClient(token string) *Client {
	return &Client{token: token}
}

// RefreshProjectCI reconciles the CI state for a project. If ci is true, it
// sets up secrets and commits the workflow. If ci is false, it removes the
// Poof-managed workflow (marker-checked) and optionally the shared secrets.
// deleteSecrets should be true only when no other CI-enabled projects share
// this repo — the caller is responsible for checking that.
func (c *Client) RefreshProjectCI(owner, repo, projectName string, ci bool, poofURL, repoToken, branch, image, folder, static string, build bool, deleteSecrets bool) error {
	if ci {
		return c.SetRepoCI(owner, repo, projectName, poofURL, repoToken, branch, image, folder, static, build)
	}
	return c.RemoveRepoCI(owner, repo, projectName, deleteSecrets)
}

// SetRepoCI sets the POOF_URL and POOF_TOKEN repo secrets and commits the
// deploy workflow file. All projects in the same repo share a single
// POOF_TOKEN secret.
func (c *Client) SetRepoCI(owner, repo, projectName, poofURL, poofToken, branch, image, folder, static string, build bool) error {
	if err := c.setSecret(owner, repo, "POOF_URL", poofURL); err != nil {
		return fmt.Errorf("set POOF_URL secret: %w", err)
	}
	if err := c.setSecret(owner, repo, "POOF_TOKEN", poofToken); err != nil {
		return fmt.Errorf("set POOF_TOKEN secret: %w", err)
	}
	if err := c.commitWorkflow(owner, repo, projectName, branch, image, folder, static, build); err != nil {
		return fmt.Errorf("commit workflow: %w", err)
	}
	return nil
}

// RemoveRepoCI deletes the Poof-managed workflow file (only if it has the
// auto-CI marker). If deleteSecrets is true (no other CI-enabled projects
// share this repo), also removes the shared POOF_TOKEN and POOF_URL secrets.
func (c *Client) RemoveRepoCI(owner, repo, projectName string, deleteSecrets bool) error {
	_ = c.deleteWorkflow(owner, repo, projectName)
	if deleteSecrets {
		c.deleteRepoSecrets(owner, repo)
	}
	return nil
}

// deleteRepoSecrets removes the shared POOF_TOKEN and POOF_URL secrets.
func (c *Client) deleteRepoSecrets(owner, repo string) {
	_ = c.deleteSecret(owner, repo, "POOF_TOKEN")
	_ = c.deleteSecret(owner, repo, "POOF_URL")
}

// --- Secrets ---

type repoPublicKey struct {
	KeyID string `json:"key_id"`
	Key   string `json:"key"`
}

func (c *Client) setSecret(owner, repo, name, value string) error {
	// Fetch the repo's NaCl public key.
	var pubKey repoPublicKey
	if err := c.get(fmt.Sprintf("/repos/%s/%s/actions/secrets/public-key", owner, repo), &pubKey); err != nil {
		return fmt.Errorf("get public key: %w", err)
	}

	encrypted, err := encryptSecret(pubKey.Key, value)
	if err != nil {
		return fmt.Errorf("encrypt secret: %w", err)
	}

	payload := map[string]string{
		"encrypted_value": encrypted,
		"key_id":          pubKey.KeyID,
	}
	return c.put(fmt.Sprintf("/repos/%s/%s/actions/secrets/%s", owner, repo, name), payload)
}

func (c *Client) deleteSecret(owner, repo, name string) error {
	return c.delete(fmt.Sprintf("/repos/%s/%s/actions/secrets/%s", owner, repo, name))
}

// encryptSecret encrypts a secret value using the repo's NaCl public key,
// as required by the GitHub Actions secrets API.
func encryptSecret(publicKeyB64, secret string) (string, error) {
	pubKeyBytes, err := base64.StdEncoding.DecodeString(publicKeyB64)
	if err != nil {
		return "", fmt.Errorf("decode public key: %w", err)
	}
	if len(pubKeyBytes) != 32 {
		return "", fmt.Errorf("unexpected public key length: %d", len(pubKeyBytes))
	}
	var recipientKey [32]byte
	copy(recipientKey[:], pubKeyBytes)

	encrypted, err := box.SealAnonymous(nil, []byte(secret), &recipientKey, rand.Reader)
	if err != nil {
		return "", fmt.Errorf("seal: %w", err)
	}
	return base64.StdEncoding.EncodeToString(encrypted), nil
}

// --- Workflow file ---

type fileContent struct {
	Message string `json:"message"`
	Content string `json:"content"` // base64
	SHA     string `json:"sha,omitempty"`
}

type getFileResponse struct {
	SHA     string `json:"sha"`
	Content string `json:"content"`
}

// imageBase strips any tag from image and returns the bare image reference.
func imageBase(image string) string {
	return strings.SplitN(image, ":", 2)[0]
}

// imagePackageName extracts the GHCR package name from an image reference.
// For "ghcr.io/owner/pkg" it returns "pkg"; for "ghcr.io/owner/sub/pkg" it
// returns "sub/pkg". Falls back to the last path component for other formats.
func imagePackageName(image string) string {
	base := imageBase(image)
	parts := strings.SplitN(base, "/", 3)
	if len(parts) == 3 {
		return parts[2]
	}
	if idx := strings.LastIndex(base, "/"); idx >= 0 {
		return base[idx+1:]
	}
	return base
}

func (c *Client) commitWorkflow(owner, repo, projectName, branch, image, folder, static string, build bool) error {
	isStatic := static == "static" || static == "spa"

	// folder support: path filter and build args
	pathsBlock := ""
	buildArgs := "."
	cleanFolder := folder
	if folder != "" {
		cleanFolder = strings.TrimRight(folder, "/")
		pathsBlock = fmt.Sprintf("    paths:\n      - \"%s/**\"", cleanFolder)
		buildArgs = fmt.Sprintf("-f %s/Dockerfile %s", cleanFolder, cleanFolder)
	}

	// Build human-readable workflow name.
	workflowName := "Poof! deploy"
	var qualifiers []string
	if isStatic {
		qualifiers = append(qualifiers, "static")
	}
	if cleanFolder != "" {
		qualifiers = append(qualifiers, cleanFolder)
	}
	if branch != defaults.Branch {
		qualifiers = append(qualifiers, branch)
	}
	if len(qualifiers) > 0 {
		workflowName += " (" + strings.Join(qualifiers, ", ") + ")"
	}

	var workflow string
	if isStatic {
		if build {
			workflow = staticWorkflowDockerTemplate
			workflow = strings.ReplaceAll(workflow, "POOF_BUILD_ARGS", buildArgs)
		} else {
			workflow = staticWorkflowDirectTemplate
			uploadFolder := "."
			if cleanFolder != "" {
				uploadFolder = cleanFolder
			}
			workflow = strings.ReplaceAll(workflow, "POOF_FOLDER", uploadFolder)
		}
	} else {
		// Container workflow (existing behavior).
		imgBase := `ghcr.io/$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')`
		pkgName := `${{ github.event.repository.name }}`
		if image != "" {
			imgBase = imageBase(image)
			pkgName = imagePackageName(image)
		}
		workflow = workflowTemplate
		workflow = strings.ReplaceAll(workflow, "POOF_IMAGE_BASE", imgBase)
		workflow = strings.ReplaceAll(workflow, "POOF_BUILD_ARGS", buildArgs)
		workflow = strings.ReplaceAll(workflow, "POOF_PKG_NAME", pkgName)
	}

	workflow = strings.ReplaceAll(workflow, "POOF_WORKFLOW_NAME", workflowName)
	workflow = strings.ReplaceAll(workflow, "POOF_BRANCH", branch)
	workflow = strings.ReplaceAll(workflow, "POOF_PATHS_BLOCK", pathsBlock)
	workflow = strings.ReplaceAll(workflow, "POOF_PROJECT_NAME", projectName)
	encoded := base64.StdEncoding.EncodeToString([]byte(workflow))

	path := fmt.Sprintf("/repos/%s/%s/contents/.github/workflows/poof-%s.yml", owner, repo, projectName)

	// Check if the file already exists (need SHA to update).
	var existing getFileResponse
	sha := ""
	if err := c.get(path, &existing); err == nil {
		sha = existing.SHA
		// Skip commit if content is unchanged.
		existingContent, err := base64.StdEncoding.DecodeString(
			strings.ReplaceAll(existing.Content, "\n", ""),
		)
		if err == nil && string(existingContent) == workflow {
			return nil
		}
	}

	payload := fileContent{
		Message: "chore: update Poof! deploy workflow",
		Content: encoded,
		SHA:     sha,
	}
	return c.put(path, payload)
}

func (c *Client) deleteWorkflow(owner, repo, projectName string) error {
	path := fmt.Sprintf("/repos/%s/%s/contents/.github/workflows/poof-%s.yml", owner, repo, projectName)

	var existing getFileResponse
	if err := c.get(path, &existing); err != nil {
		return nil // file doesn't exist, nothing to delete
	}

	// Only delete files that start with the Poof auto-CI marker.
	// This protects custom workflow files the user may have created.
	content, err := base64.StdEncoding.DecodeString(
		strings.ReplaceAll(existing.Content, "\n", ""),
	)
	if err != nil {
		return fmt.Errorf("decode workflow content: %w", err)
	}
	firstLine, _, _ := strings.Cut(string(content), "\n")
	if !strings.HasPrefix(firstLine, workflowMarker) {
		return nil // not a Poof-managed file, leave it alone
	}

	payload := map[string]string{
		"message": "chore: remove Poof! deploy workflow",
		"sha":     existing.SHA,
	}

	body, _ := json.Marshal(payload)
	req, err := http.NewRequest("DELETE", apiBase+path, bytes.NewReader(body))
	if err != nil {
		return err
	}
	req.Header.Set("Authorization", "Bearer "+c.token)
	req.Header.Set("Content-Type", "application/json")
	req.Header.Set("Accept", "application/vnd.github+json")

	resp, err := http.DefaultClient.Do(req)
	if err != nil {
		return err
	}
	defer resp.Body.Close()
	if resp.StatusCode >= 400 {
		b, _ := io.ReadAll(resp.Body)
		return fmt.Errorf("GitHub API %s: %s", resp.Status, string(b))
	}
	return nil
}

// --- HTTP helpers ---

func (c *Client) get(path string, out interface{}) error {
	req, err := http.NewRequest("GET", apiBase+path, nil)
	if err != nil {
		return err
	}
	req.Header.Set("Authorization", "Bearer "+c.token)
	req.Header.Set("Accept", "application/vnd.github+json")

	resp, err := http.DefaultClient.Do(req)
	if err != nil {
		return err
	}
	defer resp.Body.Close()
	if resp.StatusCode >= 400 {
		b, _ := io.ReadAll(resp.Body)
		return fmt.Errorf("GitHub API %s: %s", resp.Status, string(b))
	}
	return json.NewDecoder(resp.Body).Decode(out)
}

func (c *Client) put(path string, payload interface{}) error {
	body, err := json.Marshal(payload)
	if err != nil {
		return err
	}
	req, err := http.NewRequest("PUT", apiBase+path, bytes.NewReader(body))
	if err != nil {
		return err
	}
	req.Header.Set("Authorization", "Bearer "+c.token)
	req.Header.Set("Content-Type", "application/json")
	req.Header.Set("Accept", "application/vnd.github+json")

	resp, err := http.DefaultClient.Do(req)
	if err != nil {
		return err
	}
	defer resp.Body.Close()
	if resp.StatusCode >= 400 {
		b, _ := io.ReadAll(resp.Body)
		return fmt.Errorf("GitHub API %s: %s", resp.Status, string(b))
	}
	return nil
}

func (c *Client) delete(path string) error {
	req, err := http.NewRequest("DELETE", apiBase+path, nil)
	if err != nil {
		return err
	}
	req.Header.Set("Authorization", "Bearer "+c.token)
	req.Header.Set("Accept", "application/vnd.github+json")

	resp, err := http.DefaultClient.Do(req)
	if err != nil {
		return err
	}
	defer resp.Body.Close()
	if resp.StatusCode >= 400 {
		b, _ := io.ReadAll(resp.Body)
		return fmt.Errorf("GitHub API %s: %s", resp.Status, string(b))
	}
	return nil
}
