package github

import (
	"strings"
	"testing"
)

func TestIsPoofManagedWorkflow(t *testing.T) {
	tests := []struct {
		name    string
		content string
		want    bool
	}{
		{
			name:    "starts with the auto-ci marker",
			content: "# [poof-auto-ci] AUTO-GENERATED BY Poof! — CHANGES MAY BE OVERRIDDEN.\nname: foo\n",
			want:    true,
		},
		{
			name:    "marker on the first line is sufficient even without trailing text",
			content: "# [poof-auto-ci]\nname: foo\n",
			want:    true,
		},
		{
			name:    "marker buried after the first line is not honored",
			content: "name: foo\n# [poof-auto-ci]\n",
			want:    false,
		},
		{
			name:    "leading whitespace before the marker disqualifies",
			content: " # [poof-auto-ci]\nname: foo\n",
			want:    false,
		},
		{
			name:    "user-authored file without the marker is not managed",
			content: "name: my CI\non: push\njobs:\n  test:\n    runs-on: ubuntu-latest\n",
			want:    false,
		},
		{
			name:    "empty content is not managed",
			content: "",
			want:    false,
		},
		{
			name:    "single-line content is fine if it starts with the marker",
			content: "# [poof-auto-ci] header only",
			want:    true,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			if got := isPoofManagedWorkflow(tt.content); got != tt.want {
				t.Errorf("isPoofManagedWorkflow(%q) = %v, want %v", tt.content, got, tt.want)
			}
		})
	}
}

func TestTriggerBlock_Managed(t *testing.T) {
	got := triggerBlock(CIModeManaged, "main", "")
	want := "on:\n  push:\n    branches: [\"main\"]\n"
	if got != want {
		t.Errorf("managed without folder:\n got: %q\nwant: %q", got, want)
	}
}

func TestTriggerBlock_ManagedWithFolder(t *testing.T) {
	got := triggerBlock(CIModeManaged, "main", "backend")
	want := "on:\n  push:\n    branches: [\"main\"]\n    paths:\n      - \"backend/**\"\n"
	if got != want {
		t.Errorf("managed with folder:\n got: %q\nwant: %q", got, want)
	}
}

func TestTriggerBlock_FolderTrailingSlashTrimmed(t *testing.T) {
	got := triggerBlock(CIModeManaged, "main", "backend/")
	if !strings.Contains(got, "\"backend/**\"") {
		t.Errorf("expected trailing-slash folder to be normalized to 'backend/**', got %q", got)
	}
}

func TestTriggerBlock_Callable(t *testing.T) {
	got := triggerBlock(CIModeCallable, "main", "backend")
	// Callable trigger ignores branch and folder — those are caller-decided.
	if strings.Contains(got, "push") {
		t.Errorf("callable trigger should not include push trigger, got: %q", got)
	}
	if strings.Contains(got, "main") || strings.Contains(got, "backend") {
		t.Errorf("callable trigger should not embed branch or folder, got: %q", got)
	}
	for _, want := range []string{
		"workflow_call:",
		"POOF_URL:",
		"POOF_TOKEN:",
		"required: true",
		"workflow_dispatch:",
	} {
		if !strings.Contains(got, want) {
			t.Errorf("callable trigger missing %q, got: %q", want, got)
		}
	}
}

func TestTriggerBlock_EmptyModeFallsBackToManaged(t *testing.T) {
	got := triggerBlock("", "main", "")
	if !strings.Contains(got, "push") || strings.Contains(got, "workflow_call") {
		t.Errorf("empty mode should default to managed (push), got: %q", got)
	}
}
