package github

import "testing"

func TestIsPoofManagedWorkflow(t *testing.T) {
	tests := []struct {
		name    string
		content string
		want    bool
	}{
		{
			name:    "starts with the auto-ci marker",
			content: "# [poof-auto-ci] AUTO-GENERATED BY Poof! — CHANGES MAY BE OVERRIDDEN.\nname: foo\n",
			want:    true,
		},
		{
			name:    "marker on the first line is sufficient even without trailing text",
			content: "# [poof-auto-ci]\nname: foo\n",
			want:    true,
		},
		{
			name:    "marker buried after the first line is not honored",
			content: "name: foo\n# [poof-auto-ci]\n",
			want:    false,
		},
		{
			name:    "leading whitespace before the marker disqualifies",
			content: " # [poof-auto-ci]\nname: foo\n",
			want:    false,
		},
		{
			name:    "user-authored file without the marker is not managed",
			content: "name: my CI\non: push\njobs:\n  test:\n    runs-on: ubuntu-latest\n",
			want:    false,
		},
		{
			name:    "empty content is not managed",
			content: "",
			want:    false,
		},
		{
			name:    "single-line content is fine if it starts with the marker",
			content: "# [poof-auto-ci] header only",
			want:    true,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			if got := isPoofManagedWorkflow(tt.content); got != tt.want {
				t.Errorf("isPoofManagedWorkflow(%q) = %v, want %v", tt.content, got, tt.want)
			}
		})
	}
}
