package github

import (
	"bytes"
	"crypto/rand"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"strings"

	"github.com/racso/poof/defaults"
	"golang.org/x/crypto/nacl/box"
)

const apiBase = "https://api.github.com"

// Workflow templates are committed into each project repo at
// .github/workflows/poof-auto-ci-<name>.yml. The filename is the contract:
// any file at that path is considered Poof-managed and will be overwritten
// on refresh / removed on disable. The leading banner ("# [poof-auto-ci] …")
// is informational only — readers are warned not to edit the file, but
// nothing about it is verified by code.
//
// Placeholders replaced at commit time:
//   POOF_TRIGGER_BLOCK → entire `on:` section, computed from ciMode
//                        (managed = push trigger; callable = workflow_call)
//   POOF_IMAGE_BASE    → Docker image base (without tag)
//   POOF_BUILD_ARGS    → docker build args ("." for root, "-f folder/Dockerfile folder" for subfolders)
//   POOF_PROJECT_NAME  → Poof! project name (may differ from GitHub repo name in monorepos)
//   POOF_PKG_NAME      → GHCR package name for cleanup
//   All projects in the same repo share a single POOF_TOKEN secret.

// CI mode strings. Kept aligned with store.CIMode* constants but redeclared
// here to avoid an import cycle (server depends on both packages).
const (
	CIModeManaged  = "managed"
	CIModeCallable = "callable"
)

// triggerBlock returns the YAML `on:` section for a workflow.
//
// For "managed" mode (the default), the workflow runs on push to the
// configured branch, optionally filtered by paths under `folder`.
//
// For "callable" mode, the workflow exposes itself as a reusable workflow
// (`on: workflow_call`) so a user-owned outer workflow can `uses:` it after
// running its own steps (tests, lint, matrices, …). It also accepts
// `workflow_dispatch` so the deploy can still be fired manually from the
// GitHub Actions UI for debugging.
func triggerBlock(ciMode, branch, folder string) string {
	if ciMode == CIModeCallable {
		return `on:
  workflow_call:
    secrets:
      POOF_URL:
        required: true
      POOF_TOKEN:
        required: true
  workflow_dispatch:
`
	}
	pathsBlock := ""
	if folder != "" {
		pathsBlock = fmt.Sprintf("    paths:\n      - \"%s/**\"\n", strings.TrimRight(folder, "/"))
	}
	return fmt.Sprintf("on:\n  push:\n    branches: [\"%s\"]\n%s", branch, pathsBlock)
}

const workflowTemplate = `# [poof-auto-ci] AUTO-GENERATED BY Poof! — CHANGES MAY BE OVERRIDDEN. DISABLE CI ON Poof! TO USE A CUSTOM FILE.
name: POOF_WORKFLOW_NAME

POOF_TRIGGER_BLOCK
permissions:
  contents: read
  packages: write

jobs:
  deploy:
    if: vars.POOF_DISABLE != '1'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build and push image
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          IMAGE=POOF_IMAGE_BASE:${{ github.sha }}
          docker build -t $IMAGE --label co.racso.poof.managed=true POOF_BUILD_ARGS
          docker push $IMAGE
          echo "IMAGE=$IMAGE" >> $GITHUB_ENV

      - name: Deploy via Poof!
        run: |
          curl -fsSL -X POST "${{ secrets.POOF_URL }}/projects/POOF_PROJECT_NAME/deploy" \
            -H "Authorization: Bearer ${{ secrets.POOF_TOKEN }}" \
            -H "Content-Type: application/json" \
            -d "{\"image\": \"${{ env.IMAGE }}\"}"

      - name: Clean up old images
        uses: actions/delete-package-versions@v5
        with:
          package-name: POOF_PKG_NAME
          package-type: container
          min-versions-to-keep: 3
          delete-only-untagged-versions: false
`

// staticWorkflowDockerTemplate is used for static projects that have a Dockerfile.
// The Dockerfile builds the site; the output is extracted from /poof in the container.
const staticWorkflowDockerTemplate = `# [poof-auto-ci] AUTO-GENERATED BY Poof! — CHANGES MAY BE OVERRIDDEN. DISABLE CI ON Poof! TO USE A CUSTOM FILE.
name: POOF_WORKFLOW_NAME

POOF_TRIGGER_BLOCK
permissions:
  contents: read

jobs:
  deploy:
    if: vars.POOF_DISABLE != '1'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build static site
        run: |
          docker build -t poof-build POOF_BUILD_ARGS
          docker create --name poof-extract poof-build
          docker cp poof-extract:/poof ./poof-output
          docker rm poof-extract

      - name: Deploy to Poof!
        run: |
          tar -czf site.tar.gz -C ./poof-output .
          curl -fsSL -X POST "${{ secrets.POOF_URL }}/projects/POOF_PROJECT_NAME/deploy/static" \
            -H "Authorization: Bearer ${{ secrets.POOF_TOKEN }}" \
            -H "Content-Type: application/gzip" \
            --data-binary @site.tar.gz
`

// staticWorkflowDirectTemplate is used for static projects without a Dockerfile.
// The source directory is tarred and uploaded directly.
const staticWorkflowDirectTemplate = `# [poof-auto-ci] AUTO-GENERATED BY Poof! — CHANGES MAY BE OVERRIDDEN. DISABLE CI ON Poof! TO USE A CUSTOM FILE.
name: POOF_WORKFLOW_NAME

POOF_TRIGGER_BLOCK
permissions:
  contents: read

jobs:
  deploy:
    if: vars.POOF_DISABLE != '1'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Deploy to Poof!
        run: |
          tar -czf /tmp/site.tar.gz --exclude=.git -C POOF_FOLDER .
          curl -fsSL -X POST "${{ secrets.POOF_URL }}/projects/POOF_PROJECT_NAME/deploy/static" \
            -H "Authorization: Bearer ${{ secrets.POOF_TOKEN }}" \
            -H "Content-Type: application/gzip" \
            --data-binary @/tmp/site.tar.gz
`

type Client struct {
	token string
}

func NewClient(token string) *Client {
	return &Client{token: token}
}

// RefreshProjectCI reconciles the CI state for a project. If ci is true, it
// sets up secrets and commits the workflow. If ci is false, it removes the
// Poof-managed workflow (marker-checked) and optionally the shared secrets.
// deleteSecrets should be true only when no other CI-enabled projects share
// this repo — the caller is responsible for checking that.
//
// ciMode selects the workflow shape ("managed" or "callable"); see
// triggerBlock for the difference. The empty string is treated as managed.
func (c *Client) RefreshProjectCI(owner, repo, projectName string, ci bool, poofURL, repoToken, branch, image, folder, static, ciMode string, build bool, deleteSecrets bool) error {
	if ci {
		return c.SetRepoCI(owner, repo, projectName, poofURL, repoToken, branch, image, folder, static, ciMode, build)
	}
	return c.RemoveRepoCI(owner, repo, projectName, deleteSecrets)
}

// SetRepoCI sets the POOF_URL and POOF_TOKEN repo secrets and commits the
// deploy workflow file. All projects in the same repo share a single
// POOF_TOKEN secret.
func (c *Client) SetRepoCI(owner, repo, projectName, poofURL, poofToken, branch, image, folder, static, ciMode string, build bool) error {
	if err := c.setSecret(owner, repo, "POOF_URL", poofURL); err != nil {
		return fmt.Errorf("set POOF_URL secret: %w", err)
	}
	if err := c.setSecret(owner, repo, "POOF_TOKEN", poofToken); err != nil {
		return fmt.Errorf("set POOF_TOKEN secret: %w", err)
	}
	if err := c.commitWorkflow(owner, repo, projectName, branch, image, folder, static, ciMode, build); err != nil {
		return fmt.Errorf("commit workflow: %w", err)
	}
	return nil
}

// RemoveRepoCI deletes the Poof-managed workflow file (only if it has the
// auto-CI marker). If deleteSecrets is true (no other CI-enabled projects
// share this repo), also removes the shared POOF_TOKEN and POOF_URL secrets.
func (c *Client) RemoveRepoCI(owner, repo, projectName string, deleteSecrets bool) error {
	_ = c.deleteWorkflow(owner, repo, projectName)
	if deleteSecrets {
		c.deleteRepoSecrets(owner, repo)
	}
	return nil
}

// deleteRepoSecrets removes the shared POOF_TOKEN and POOF_URL secrets.
func (c *Client) deleteRepoSecrets(owner, repo string) {
	_ = c.deleteSecret(owner, repo, "POOF_TOKEN")
	_ = c.deleteSecret(owner, repo, "POOF_URL")
}

// --- Secrets ---

type repoPublicKey struct {
	KeyID string `json:"key_id"`
	Key   string `json:"key"`
}

func (c *Client) setSecret(owner, repo, name, value string) error {
	// Fetch the repo's NaCl public key.
	var pubKey repoPublicKey
	if err := c.get(fmt.Sprintf("/repos/%s/%s/actions/secrets/public-key", owner, repo), &pubKey); err != nil {
		return fmt.Errorf("get public key: %w", err)
	}

	encrypted, err := encryptSecret(pubKey.Key, value)
	if err != nil {
		return fmt.Errorf("encrypt secret: %w", err)
	}

	payload := map[string]string{
		"encrypted_value": encrypted,
		"key_id":          pubKey.KeyID,
	}
	return c.put(fmt.Sprintf("/repos/%s/%s/actions/secrets/%s", owner, repo, name), payload)
}

func (c *Client) deleteSecret(owner, repo, name string) error {
	return c.delete(fmt.Sprintf("/repos/%s/%s/actions/secrets/%s", owner, repo, name))
}

// encryptSecret encrypts a secret value using the repo's NaCl public key,
// as required by the GitHub Actions secrets API.
func encryptSecret(publicKeyB64, secret string) (string, error) {
	pubKeyBytes, err := base64.StdEncoding.DecodeString(publicKeyB64)
	if err != nil {
		return "", fmt.Errorf("decode public key: %w", err)
	}
	if len(pubKeyBytes) != 32 {
		return "", fmt.Errorf("unexpected public key length: %d", len(pubKeyBytes))
	}
	var recipientKey [32]byte
	copy(recipientKey[:], pubKeyBytes)

	encrypted, err := box.SealAnonymous(nil, []byte(secret), &recipientKey, rand.Reader)
	if err != nil {
		return "", fmt.Errorf("seal: %w", err)
	}
	return base64.StdEncoding.EncodeToString(encrypted), nil
}

// --- Workflow file ---

type fileContent struct {
	Message string `json:"message"`
	Content string `json:"content"` // base64
	SHA     string `json:"sha,omitempty"`
}

type getFileResponse struct {
	SHA     string `json:"sha"`
	Content string `json:"content"`
}

// workflowPath returns the GitHub Contents API path for a project's
// Poof-managed workflow file. The trailing filename is the contract:
// any file at this path is considered Poof's and will be overwritten
// or removed without further checks.
func workflowPath(owner, repo, projectName string) string {
	return fmt.Sprintf("/repos/%s/%s/contents/%s", owner, repo, workflowFileNew(projectName))
}

// workflowFileNew is the canonical (post-v0.16.0) path to a project's
// Poof-managed workflow file, relative to the repo root.
func workflowFileNew(projectName string) string {
	return fmt.Sprintf(".github/workflows/poof-auto-ci-%s.yml", projectName)
}

// workflowFileLegacy is the pre-v0.16.0 path. Only referenced by the
// migration diagnostic; production code never writes here.
func workflowFileLegacy(projectName string) string {
	return fmt.Sprintf(".github/workflows/poof-%s.yml", projectName)
}

// imageBase strips any tag from image and returns the bare image reference.
func imageBase(image string) string {
	return strings.SplitN(image, ":", 2)[0]
}

// imagePackageName extracts the GHCR package name from an image reference.
// For "ghcr.io/owner/pkg" it returns "pkg"; for "ghcr.io/owner/sub/pkg" it
// returns "sub/pkg". Falls back to the last path component for other formats.
func imagePackageName(image string) string {
	base := imageBase(image)
	parts := strings.SplitN(base, "/", 3)
	if len(parts) == 3 {
		return parts[2]
	}
	if idx := strings.LastIndex(base, "/"); idx >= 0 {
		return base[idx+1:]
	}
	return base
}

func (c *Client) commitWorkflow(owner, repo, projectName, branch, image, folder, static, ciMode string, build bool) error {
	isStatic := static == "static" || static == "spa"
	isCallable := ciMode == CIModeCallable

	// folder support: build args (path filter goes through triggerBlock)
	buildArgs := "."
	cleanFolder := folder
	if folder != "" {
		cleanFolder = strings.TrimRight(folder, "/")
		buildArgs = fmt.Sprintf("-f %s/Dockerfile %s", cleanFolder, cleanFolder)
	}

	// Build human-readable workflow name.
	workflowName := "Poof! deploy"
	var qualifiers []string
	if isStatic {
		qualifiers = append(qualifiers, "static")
	}
	if cleanFolder != "" {
		qualifiers = append(qualifiers, cleanFolder)
	}
	if branch != defaults.Branch && !isCallable {
		qualifiers = append(qualifiers, branch)
	}
	if isCallable {
		qualifiers = append(qualifiers, "callable")
	}
	if len(qualifiers) > 0 {
		workflowName += " (" + strings.Join(qualifiers, ", ") + ")"
	}

	var workflow string
	if isStatic {
		if build {
			workflow = staticWorkflowDockerTemplate
			workflow = strings.ReplaceAll(workflow, "POOF_BUILD_ARGS", buildArgs)
		} else {
			workflow = staticWorkflowDirectTemplate
			uploadFolder := "."
			if cleanFolder != "" {
				uploadFolder = cleanFolder
			}
			workflow = strings.ReplaceAll(workflow, "POOF_FOLDER", uploadFolder)
		}
	} else {
		// Container workflow (existing behavior).
		imgBase := `ghcr.io/$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')`
		pkgName := `${{ github.event.repository.name }}`
		if image != "" {
			imgBase = imageBase(image)
			pkgName = imagePackageName(image)
		}
		workflow = workflowTemplate
		workflow = strings.ReplaceAll(workflow, "POOF_IMAGE_BASE", imgBase)
		workflow = strings.ReplaceAll(workflow, "POOF_BUILD_ARGS", buildArgs)
		workflow = strings.ReplaceAll(workflow, "POOF_PKG_NAME", pkgName)
	}

	workflow = strings.ReplaceAll(workflow, "POOF_WORKFLOW_NAME", workflowName)
	workflow = strings.ReplaceAll(workflow, "POOF_TRIGGER_BLOCK", triggerBlock(ciMode, branch, cleanFolder))
	workflow = strings.ReplaceAll(workflow, "POOF_PROJECT_NAME", projectName)
	encoded := base64.StdEncoding.EncodeToString([]byte(workflow))

	path := workflowPath(owner, repo, projectName)

	// Fetch the current SHA (required to update an existing file). If the
	// file doesn't exist, sha stays empty and the PUT creates it. If it
	// does exist and the content already matches, skip the commit.
	var existing getFileResponse
	sha := ""
	if err := c.get(path, &existing); err == nil {
		sha = existing.SHA
		existingContent, decodeErr := base64.StdEncoding.DecodeString(
			strings.ReplaceAll(existing.Content, "\n", ""),
		)
		if decodeErr == nil && string(existingContent) == workflow {
			return nil
		}
	}

	payload := fileContent{
		Message: "chore: update Poof! deploy workflow",
		Content: encoded,
		SHA:     sha,
	}
	return c.put(path, payload)
}

func (c *Client) deleteWorkflow(owner, repo, projectName string) error {
	path := workflowPath(owner, repo, projectName)

	var existing getFileResponse
	if err := c.get(path, &existing); err != nil {
		return nil // file doesn't exist, nothing to delete
	}

	payload := map[string]string{
		"message": "chore: remove Poof! deploy workflow",
		"sha":     existing.SHA,
	}

	body, _ := json.Marshal(payload)
	req, err := http.NewRequest("DELETE", apiBase+path, bytes.NewReader(body))
	if err != nil {
		return err
	}
	req.Header.Set("Authorization", "Bearer "+c.token)
	req.Header.Set("Content-Type", "application/json")
	req.Header.Set("Accept", "application/vnd.github+json")

	resp, err := http.DefaultClient.Do(req)
	if err != nil {
		return err
	}
	defer resp.Body.Close()
	if resp.StatusCode >= 400 {
		b, _ := io.ReadAll(resp.Body)
		return fmt.Errorf("GitHub API %s: %s", resp.Status, string(b))
	}
	return nil
}

// --- Workflow migration diagnostic ---

// WorkflowDiagnostic describes the GitHub state of a single project's
// Poof-managed workflow file, used by `poof migrate workflows`.
//
// All booleans report observed facts; classification (which actions are
// safe, what summary state to display) is left to the caller so new
// states can be added without server-side changes.
type WorkflowDiagnostic struct {
	Project          string              `json:"project"`
	Repo             string              `json:"repo"` // "owner/repo"
	CI               bool                `json:"ci"`
	OldPath          string              `json:"old_path"`
	NewPath          string              `json:"new_path"`
	OldPathExists    bool                `json:"old_path_exists"`
	OldPathHasMarker bool                `json:"old_path_has_marker"`
	NewPathExists    bool                `json:"new_path_exists"`
	References       []WorkflowReference `json:"references,omitempty"`
	// Error is set when the diagnostic could not be completed (e.g. GitHub
	// API failure). Other fields may be partially populated.
	Error string `json:"error,omitempty"`
}

// WorkflowReference is a `uses:` (or similar) reference to a project's
// legacy workflow path found in some other workflow file in the repo.
type WorkflowReference struct {
	Path string `json:"path"` // e.g. ".github/workflows/clip-api.yml"
	Line int    `json:"line"` // 1-based
	Hint string `json:"hint"` // trimmed line content
}

// DeleteLegacyWorkflow removes a project's pre-v0.16.0 workflow file
// (.github/workflows/poof-<name>.yml). Idempotent: returns nil if the
// file is already absent. Used by `poof migrate workflows --apply` to
// clean up after the rename to the canonical path.
func (c *Client) DeleteLegacyWorkflow(owner, repo, projectName string) error {
	apiPath := fmt.Sprintf("/repos/%s/%s/contents/%s", owner, repo, workflowFileLegacy(projectName))
	var existing getFileResponse
	found, err := c.getMaybe(apiPath, &existing)
	if err != nil {
		return err
	}
	if !found {
		return nil
	}

	payload := map[string]string{
		"message": "chore: remove legacy Poof! workflow path",
		"sha":     existing.SHA,
	}
	body, _ := json.Marshal(payload)
	req, err := http.NewRequest("DELETE", apiBase+apiPath, bytes.NewReader(body))
	if err != nil {
		return err
	}
	req.Header.Set("Authorization", "Bearer "+c.token)
	req.Header.Set("Content-Type", "application/json")
	req.Header.Set("Accept", "application/vnd.github+json")

	resp, err := http.DefaultClient.Do(req)
	if err != nil {
		return err
	}
	defer resp.Body.Close()
	if resp.StatusCode >= 400 {
		b, _ := io.ReadAll(resp.Body)
		return fmt.Errorf("GitHub API %s: %s", resp.Status, string(b))
	}
	return nil
}

// WorkflowMigrationDiagnostic gathers the GitHub-side state needed to
// decide whether a project's workflow file should be renamed from the
// pre-v0.16.0 path to the canonical poof-auto-ci-<name>.yml.
//
// `ci` is the project's CI flag (passed in by the caller; we don't
// re-derive it from GitHub). It's threaded through onto the result so
// the CLI can decide what's expected vs unexpected at a glance.
func (c *Client) WorkflowMigrationDiagnostic(owner, repo, projectName string, ci bool) (*WorkflowDiagnostic, error) {
	d := &WorkflowDiagnostic{
		Project: projectName,
		Repo:    fmt.Sprintf("%s/%s", owner, repo),
		CI:      ci,
		OldPath: workflowFileLegacy(projectName),
		NewPath: workflowFileNew(projectName),
	}

	// Old path
	oldContent, found, err := c.getFileContent(owner, repo, d.OldPath)
	if err != nil {
		d.Error = fmt.Sprintf("checking %s: %v", d.OldPath, err)
		return d, nil
	}
	d.OldPathExists = found
	if found {
		firstLine, _, _ := strings.Cut(oldContent, "\n")
		d.OldPathHasMarker = strings.HasPrefix(firstLine, workflowMarkerBanner)
	}

	// New path
	_, newFound, err := c.getFileContent(owner, repo, d.NewPath)
	if err != nil {
		d.Error = fmt.Sprintf("checking %s: %v", d.NewPath, err)
		return d, nil
	}
	d.NewPathExists = newFound

	// References — only relevant if the old file still exists. For an
	// already-migrated project there's nothing to point at.
	if d.OldPathExists {
		refs, err := c.findWorkflowReferences(owner, repo, d.OldPath, d.NewPath)
		if err != nil {
			// Non-fatal: report what we have plus the error.
			d.Error = fmt.Sprintf("scanning references: %v", err)
		} else {
			d.References = refs
		}
	}

	return d, nil
}

// workflowMarkerBanner is the leading line Poof has historically written
// at the top of each managed workflow file. As of v0.16.0 it carries no
// behavioral meaning, but the migration diagnostic reads it as a signal
// that an old-path file is very likely Poof's (and not user-authored).
const workflowMarkerBanner = "# [poof-auto-ci]"

type contentsListEntry struct {
	Name string `json:"name"`
	Path string `json:"path"`
	Type string `json:"type"`
}

// getFileContent fetches a single file's content, returning ("", false, nil)
// when the file does not exist (404). Any other error is propagated.
func (c *Client) getFileContent(owner, repo, repoPath string) (string, bool, error) {
	apiPath := fmt.Sprintf("/repos/%s/%s/contents/%s", owner, repo, repoPath)
	var f getFileResponse
	found, err := c.getMaybe(apiPath, &f)
	if err != nil || !found {
		return "", found, err
	}
	content, err := base64.StdEncoding.DecodeString(strings.ReplaceAll(f.Content, "\n", ""))
	if err != nil {
		return "", true, fmt.Errorf("decode content: %w", err)
	}
	return string(content), true, nil
}

// findWorkflowReferences grep-scans every other workflow file in
// .github/workflows/ for a `./<oldPath>` reference. Used by the migration
// diagnostic to surface user-owned outer workflows whose `uses:` target
// would break after the rename.
func (c *Client) findWorkflowReferences(owner, repo, oldPath, newPath string) ([]WorkflowReference, error) {
	apiPath := fmt.Sprintf("/repos/%s/%s/contents/.github/workflows", owner, repo)
	var entries []contentsListEntry
	found, err := c.getMaybe(apiPath, &entries)
	if err != nil || !found {
		return nil, err
	}

	needle := "./" + oldPath
	var refs []WorkflowReference
	for _, e := range entries {
		if e.Type != "file" {
			continue
		}
		// Skip the project's own old/new workflow files; we're hunting
		// for references in user-owned workflows, not Poof's own.
		if e.Path == oldPath || e.Path == newPath {
			continue
		}
		if !strings.HasSuffix(e.Name, ".yml") && !strings.HasSuffix(e.Name, ".yaml") {
			continue
		}
		content, _, err := c.getFileContent(owner, repo, e.Path)
		if err != nil {
			continue
		}
		for i, line := range strings.Split(content, "\n") {
			if strings.Contains(line, needle) {
				refs = append(refs, WorkflowReference{
					Path: e.Path,
					Line: i + 1,
					Hint: strings.TrimSpace(line),
				})
			}
		}
	}
	return refs, nil
}

// --- HTTP helpers ---

func (c *Client) get(path string, out interface{}) error {
	req, err := http.NewRequest("GET", apiBase+path, nil)
	if err != nil {
		return err
	}
	req.Header.Set("Authorization", "Bearer "+c.token)
	req.Header.Set("Accept", "application/vnd.github+json")

	resp, err := http.DefaultClient.Do(req)
	if err != nil {
		return err
	}
	defer resp.Body.Close()
	if resp.StatusCode >= 400 {
		b, _ := io.ReadAll(resp.Body)
		return fmt.Errorf("GitHub API %s: %s", resp.Status, string(b))
	}
	return json.NewDecoder(resp.Body).Decode(out)
}

// getMaybe is like get, but distinguishes 404 from other errors. The
// returned `found` flag is false on 404 (with a nil error); other 4xx/5xx
// or transport failures still come back as errors. Useful for diagnostic
// flows that want to ask "does this file exist?" without papering over
// real failures.
func (c *Client) getMaybe(path string, out interface{}) (found bool, err error) {
	req, err := http.NewRequest("GET", apiBase+path, nil)
	if err != nil {
		return false, err
	}
	req.Header.Set("Authorization", "Bearer "+c.token)
	req.Header.Set("Accept", "application/vnd.github+json")

	resp, err := http.DefaultClient.Do(req)
	if err != nil {
		return false, err
	}
	defer resp.Body.Close()
	if resp.StatusCode == http.StatusNotFound {
		return false, nil
	}
	if resp.StatusCode >= 400 {
		b, _ := io.ReadAll(resp.Body)
		return false, fmt.Errorf("GitHub API %s: %s", resp.Status, string(b))
	}
	if out != nil {
		if err := json.NewDecoder(resp.Body).Decode(out); err != nil {
			return false, fmt.Errorf("decode response: %w", err)
		}
	}
	return true, nil
}

func (c *Client) put(path string, payload interface{}) error {
	body, err := json.Marshal(payload)
	if err != nil {
		return err
	}
	req, err := http.NewRequest("PUT", apiBase+path, bytes.NewReader(body))
	if err != nil {
		return err
	}
	req.Header.Set("Authorization", "Bearer "+c.token)
	req.Header.Set("Content-Type", "application/json")
	req.Header.Set("Accept", "application/vnd.github+json")

	resp, err := http.DefaultClient.Do(req)
	if err != nil {
		return err
	}
	defer resp.Body.Close()
	if resp.StatusCode >= 400 {
		b, _ := io.ReadAll(resp.Body)
		return fmt.Errorf("GitHub API %s: %s", resp.Status, string(b))
	}
	return nil
}

func (c *Client) delete(path string) error {
	req, err := http.NewRequest("DELETE", apiBase+path, nil)
	if err != nil {
		return err
	}
	req.Header.Set("Authorization", "Bearer "+c.token)
	req.Header.Set("Accept", "application/vnd.github+json")

	resp, err := http.DefaultClient.Do(req)
	if err != nil {
		return err
	}
	defer resp.Body.Close()
	if resp.StatusCode >= 400 {
		b, _ := io.ReadAll(resp.Body)
		return fmt.Errorf("GitHub API %s: %s", resp.Status, string(b))
	}
	return nil
}
